### PR TITLE
Add clustering module to API docs generator

### PR DESCRIPTION
**Pull request by arovir01**
This PR adds the clustering module to `python/core/api` and updates `build_docs.py` to generate the correct API documentation for clustering.

### CODE REVIEW

**Comment by arovir01** [comment]
@alanchiao Could you please review this?

**Comment by alanchiao** [comment]
@arovir01: take a look at https://github.com/tensorflow/model-optimization/pull/427, for what would be better. 

Afterwards, we should wait until just a bit prior to launch to submit this PR, since it'll otherwise show up the API docs as launched. 

If you want to test the actual imports earlier, we can start by submitting a version that
1) has all the right changes under core/api
2) under build_docs.py, blacklist everything clustering API so that nothing shows up in the API docs. 

And then all the colabs can update to their final versions with the `import tensorflow_model_optimization as tfmot` style imports.

**Comment by arovir01** [comment]
> @arovir01: take a look at #427, for what would be better.

I removed the wildcard import, as suggested. I will leave the rest as it is until we are ready to sumbit this change.

**Comment by alanchiao** [comment]
Looks good. Could you add the additional CentroidInitialization enum? @Ruomei

Keeping it in the same location (as in tfmot.clustering.keras.CentroidInitialization) seems ok in my opinion.

On the side, noticed that CentroidInitialization doesn't have any API docs. https://www.tensorflow.org/api_docs/python/tf/distribute/ReduceOp as an example.
`cluster_weights` can instead directly reference the `CentroidInitialization` class in its docs and people can go to
`CentroidInitialization''s API docs to understand the differences between the three (like https://www.tensorflow.org/api_docs/python/tf/keras/estimator/model_to_estimator).

**Comment by arovir01** [comment]
> Could you add the additional CentroidInitialization enum?

Done.
 
> On the side, noticed that CentroidInitialization doesn't have any API docs. https://www.tensorflow.org/api_docs/python/tf/distribute/ReduceOp as an example.
> `cluster_weights` can instead directly reference the `CentroidInitialization` class in its docs and people can go to
> `CentroidInitialization''s API docs to understand the differences between the three (like the references to tf.keras.layers.Layer in https://www.tensorflow.org/api_docs/python/tf/keras/estimator/model_to_estimator).

Good point. Will do this in a separate PR, as it is a somewhat distinct piece of work.

**Comment by Ruomei** [comment]
Thanks! @Áron Virginás-Tar<mailto:notifications@github.com>
________________________________

**Comment by arovir01** [comment]
> Will do this in a separate PR, as it is a somewhat distinct piece of work.

[PR](https://github.com/tensorflow/model-optimization/pull/467) created.

**Comment by akarmi** [comment]
@alanchiao, can you please review the recent changes?

**Comment by alanchiao** [comment]
Looks good - though it is missing changes to python/core/api/BUILD.

Documentation is under final review so will go ahead and merge this while making the necessary changes to BUILD.

**Comment by arovir01** [comment]
> it is missing changes to python/core/api/BUILD

Noted.

**Pull request merged**
