### PR TITLE
Fix for tensorflow_model_optimization import error

### PR DESCRIPTION
**Pull request by SaoirseARM**
This PR fixes import issues seen.

When trying the following: 
`import tensorflow_model_optimization as tfmot`

the following error occurs: 
`ModuleNotFoundError: No module named 'tensorflow_model_optimization.python.core.quantization.keras.experimental'`

### CODE REVIEW

**Comment by fredrec** [comment]
Thanks @SaoirseARM,

Is this still a issue ? I cannot reproduce with master nor with the latest version on PyPi (`tensorflow-model-optimization==0.7.0`).


This is the setup to try to reproduce:
```
#!/bin/bash
set -eux

# Create an isolated Python environment
mkdir -p venv
virtualenv ./venv
source ./venv/bin/activate

# Install tensorflow and TFMOT
pip install tensorflow==2.7.0
python setup.py install
# or install the latest version from PyPI:
# pip install tensorflow-model-optimization==0.7.0

# Try to import TFMOT
python -c "import tensorflow_model_optimization as tfmot"
```

**Comment by SaoirseARM** [comment]
Hi @fredrec , thank you for the reply. Unfortunately this seems to still be an issue, if we alter your script slightly to run import from another directory, the following still occurs: 
`ModuleNotFoundError: No module named 'tensorflow_model_optimization.python.core.quantization.keras.experimental'`

Setup to reproduce:
```
#!/bin/bash
set -eux

# Create an isolated Python environment
mkdir -p venv
virtualenv ./venv
source ./venv/bin/activate

# Install tensorflow and TFMOT
pip install tensorflow==2.7.0
python setup.py install
# or install the latest version from PyPI:
# pip install tensorflow-model-optimization==0.7.0

# Run import check from /tmp directory
cd /tmp
# Try to import TFMOT
python -c "import tensorflow_model_optimization as tfmot" 
```

If you need any more information, please let me know. Thanks!

**Review by fredrec — APPROVED** [review]
Thanks a lot @SaoirseARM !

**Comment by fredrec** [comment]
Ohh wow. Indeed, trying to import from the root of the repository was not the smartest thing to do..

I will apply your fix and also add this test in the CI, to prevent such things to occur again in the future.
Thanks!

**Pull request merged**
