### PR TITLE
Revert "Small tidy up: Removed unused leftover variables."

### PR DESCRIPTION
**Pull request by benkli01**
This reverts commit 7b7fe538640c484388dbce4390d126d57c070f91 (see PR #557 for discussion) that causes problems and was accidentally merged.

### CODE REVIEW

**Comment by alanchiao** [comment]
Looks good to me. From a process point of view, someone from your side should approve and add the ready to pull label.

**Review by alanchiao — APPROVED** [review]

**Comment by alanchiao** [comment]
Would be good for someone to write a unit test in a future PR for this.

**Review by akarmi — APPROVED** [review]
Thanks @benkli01. Could you please create an internal issue to add the unit tests requested by Alan?

**Comment by benkli01** [comment]
> 
> 
> Thanks @benkli01. Could you please create an internal issue to add the unit tests requested by Alan?

Done.

**Pull request merged**
